import type { Metadata } from "next";
import Link from "next/link";
import { LegalPage, H2, P, UL } from "@/components/marketing/LegalPage";
import { COMPANY_LEGAL_NAME, LEGAL_ADDRESS, PRIVACY_EMAIL, SUBPROCESSORS, SUPPORT_EMAIL } from "@/components/marketing/site";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "How CallCatch collects, uses, shares and deletes personal information for business customers, their callers and website visitors.",
  alternates: { canonical: "/privacy" },
};

export default function PrivacyPage() {
  return (
    <LegalPage
      title="Privacy Policy"
      summary="We collect what we need to answer missed calls and lead forms on behalf of the businesses that use CallCatch, to run their accounts, and to run our own website. We don't sell personal information, and mobile phone numbers and text consent are never shared with third parties for marketing."
    >
      <H2 id="who">1. Who we are and who this covers</H2>
      <P>
        This policy is published by {COMPANY_LEGAL_NAME} (&ldquo;CallCatch&rdquo;, &ldquo;we&rdquo;, &ldquo;us&rdquo;), {LEGAL_ADDRESS}. It covers three groups of people:
      </P>
      <UL
        items={[
          <>
            <strong>Customers</strong> — owners and staff of the home-service businesses (&ldquo;Businesses&rdquo;) that sign up for CallCatch.
          </>,
          <>
            <strong>Callers and leads</strong> — people who call a Business, leave a voicemail, text with it, or submit its lead form. For these people the Business is the data controller and we act as its service provider (processor); this policy explains what we do on the Business&apos;s behalf.
          </>,
          <>
            <strong>Website visitors</strong> — anyone visiting callcatch.co, including people who call our demo line.
          </>,
        ]}
      />

      <H2 id="collect">2. What we collect</H2>
      <P>
        <strong>From Customers:</strong> name, email, password (hashed by our authentication provider), business legal name and DBA, address, EIN (required by carriers to verify a business phone number), website, business phone number, alert mobile number, time zone, service area, hours, services offered, booking links, billing details (handled by Stripe — we store only a customer id, plan, and the last four digits and brand of the card), and usage of the app (pages viewed, actions taken, IP address, browser).
      </P>
      <P>
        <strong>From callers and leads (on behalf of a Business):</strong> phone number, caller name if provided by the carrier or the caller, the time and duration of calls, voicemail audio recordings and their transcripts, the content of text messages exchanged with the Business (including messages generated by our automated assistant), service address and job details the caller shares, lead-form fields (name, phone, email, answers), consent records (when, from which number, through which channel), and delivery metadata from carriers.
      </P>
      <P>
        <strong>From website visitors:</strong> IP address, browser and device information, pages viewed, referrer, UTM parameters and ad click identifiers (such as Meta&apos;s <code>fbclid</code>), stored in a first-party cookie so we can measure which ads work. If you call the demo line we collect your phone number and the demo conversation.
      </P>

      <H2 id="use">3. How we use it</H2>
      <UL
        items={[
          "To answer missed calls and lead forms on behalf of a Business: send the text-back, ask qualification questions, transcribe voicemail, summarize the conversation and alert the Business.",
          "To run Customer accounts: authentication, billing, carrier verification filings, alerts, the shared inbox, weekly reports and support.",
          "To operate the automated assistant: message content and the Business's profile are sent to our AI provider (Anthropic) to generate replies and summaries. Anthropic does not use API data to train its models.",
          "To keep the service safe and lawful: honoring STOP/HELP, enforcing quiet hours, preventing abuse, and keeping records required by carriers and regulators.",
          "To measure and improve our own marketing: aggregate analytics and ad conversion measurement (see Cookies and advertising below). We never use callers' or leads' data for our own marketing.",
        ]}
      />

      <H2 id="share">4. Who we share it with</H2>
      <P>We share personal information only with the service providers below, each under a written agreement limiting their use to providing the service to us, and only with the data each one needs:</P>
      <div className="overflow-x-auto rounded-2xl border border-brand-100">
        <table className="w-full min-w-[520px] text-left text-sm">
          <thead className="bg-brand-50 text-brand-900">
            <tr>
              <th scope="col" className="px-3 py-2 font-semibold">Subprocessor</th>
              <th scope="col" className="px-3 py-2 font-semibold">Purpose</th>
              <th scope="col" className="px-3 py-2 font-semibold">Location</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-brand-100">
            {SUBPROCESSORS.map((s) => (
              <tr key={s.name}>
                <th scope="row" className="px-3 py-2 font-medium text-brand-900">{s.name}</th>
                <td className="px-3 py-2">{s.purpose}</td>
                <td className="px-3 py-2">{s.location}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
      <P>
        We also share information (a) with the Business a caller contacted — that is the point of the service; (b) with carriers and messaging aggregators as required to register phone numbers and deliver messages; (c) when required by law, subpoena or to protect people&apos;s safety; and (d) with a successor if we sell or merge the company, under this same policy.
      </P>
      <P>
        <strong>We do not sell personal information.</strong> <strong>No mobile information will be shared with third parties or affiliates for marketing or promotional purposes.</strong> Text messaging originator opt-in data and consent are not shared with any third parties except as needed to deliver the messages.
      </P>

      <H2 id="cookies">5. Cookies and advertising measurement</H2>
      <P>
        Our marketing site uses a first-party cookie (<code>cc_attr</code>, 90 days) to remember the ad campaign and click id that brought you here, and the Meta Pixel with the Meta Conversions API to tell Meta when a visit from one of our ads leads to a demo call, signup or purchase. When we send an event to Meta we hash your email and phone number (SHA-256) before sending; Meta uses the hash only to match the event to its own users. You can opt out of Meta&apos;s ad personalization in your Facebook settings, block third-party scripts in your browser, or enable Global Privacy Control, which we honor. The app itself (after login) does not load advertising trackers. Necessary cookies keep you signed in.
      </P>

      <H2 id="retention">6. Retention</H2>
      <UL
        items={[
          "Call, message and lead records (including voicemail audio and transcripts): kept while the Business's account is active so the Business can see its history, and deleted within 30 days of a verified deletion request from the Business (see the Data Deletion page). A Business can also ask us to delete an individual caller's records at any time.",
          "Consent and opt-out records: kept for 4 years after the last message, as carrier rules and the TCPA statute of limitations require, even if other data is deleted.",
          "Demo-line conversations: kept so we can show you the owner's view of your demo call; deleted within 30 days of your request (reply STOP to the demo text or email us).",
          "Customer account and billing records: for the life of the account plus 7 years for tax and accounting.",
          "Website analytics and attribution: 90 days (cookie) / 26 months (aggregate).",
        ]}
      />

      <H2 id="rights">7. Your choices and rights</H2>
      <P>
        Anyone can request access to, correction of, or deletion of their personal information by emailing <a className="underline" href={`mailto:${PRIVACY_EMAIL}`}>{PRIVACY_EMAIL}</a>; see our{" "}
        <Link href="/data-deletion" className="underline">
          Data Deletion
        </Link>{" "}
        page for the exact steps and timelines. Callers can stop texts at any time by replying STOP. If you are a caller and want data deleted, we will act on the Business&apos;s instruction or, if the Business does not respond within 10 days, on yours. Residents of California, Colorado, Connecticut, Virginia, Utah, Texas, Oregon and other states with privacy laws have the rights those laws grant, including the right not to be discriminated against for exercising them, and may appeal a decision by replying to our response. We do not knowingly collect information from children under 16; if you believe we have, email us and we will delete it.
      </P>

      <H2 id="security">8. Security</H2>
      <P>
        Data is encrypted in transit (TLS) and at rest by our hosting providers. Access to production data is limited to personnel who need it, protected by multi-factor authentication, and logged. Customer accounts are isolated with row-level security. Secrets (API keys, tokens) are stored only in our hosting provider&apos;s encrypted configuration, never in the browser. No system is perfectly secure; if we learn of a breach affecting you we will notify you and the relevant authorities as the law requires.
      </P>

      <H2 id="international">9. Where data is processed</H2>
      <P>CallCatch serves businesses in the United States and processes data in the United States. If you use the service from elsewhere, your information will be transferred to and processed in the US.</P>

      <H2 id="changes">10. Changes and contact</H2>
      <P>
        We will post any changes here and update the date at the top; for material changes we will email Customers. Questions or requests: <a className="underline" href={`mailto:${PRIVACY_EMAIL}`}>{PRIVACY_EMAIL}</a> (privacy) or <a className="underline" href={`mailto:${SUPPORT_EMAIL}`}>{SUPPORT_EMAIL}</a> (support). {COMPANY_LEGAL_NAME}, {LEGAL_ADDRESS}.
      </P>
    </LegalPage>
  );
}
